# Generated by Django 5.2.7 on 2025-12-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="ost",
            new_name="post",
        ),
    ]
